name: Build WallChess Debug APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build Debug APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '24'

      - name: Install Cordova
        run: npm install -g cordova

      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Install Gradle
        uses: gradle/gradle-build-action@v2

      - name: Install Android SDK
        run: |
          mkdir -p $HOME/Android/Sdk
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline-tools.zip
          unzip cmdline-tools.zip -d $HOME/Android/Sdk
          yes | $HOME/Android/Sdk/cmdline-tools/bin/sdkmanager --sdk_root=$HOME/Android/Sdk "platform-tools" "platforms;android-33" "build-tools;33.0.2"
          echo "export ANDROID_SDK_ROOT=$HOME/Android/Sdk" >> $GITHUB_ENV
          echo "$HOME/Android/Sdk/platform-tools" >> $GITHUB_PATH

      - name: Build Debug APK
        run: |
          cd WallChess   # Change this if your project folder has a different name
          cordova platform add android || echo "Platform already added"
          cordova build android

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: WallChess-Debug-APK
          path: WallChess/platforms/android/app/build/outputs/apk/debug/app-debug.apk
